name: Check Users API

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl postgresql-client

      - name: Check Users API
        id: api_check
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://related-certain-frog.ngrok-free.app/users)
          if [ "$STATUS" -eq 200 ]; then
            RESULT='UP'
          else
            RESULT='DOWN'
          fi
          echo "status=$RESULT" >> $GITHUB_OUTPUT

      - name: Insert status into DB
        env:
          DB_URL: ${{ secrets.NEON_CONN }}
        run: |
          psql "$DB_URL" <<EOF
          INSERT INTO server_status (server_name, status, checked_at, timestamp_local)
          VALUES (
            'Users API',
            '${{ steps.api_check.outputs.status }}' = 'UP',
            NOW(),
            (NOW() AT TIME ZONE 'UTC') + INTERVAL '8 hours'
          );
          EOF
